name: dl_cooperativity
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - ld_impl_linux-64=2.36.1
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libuuid=2.32.1
  - libzlib=1.2.11
  - ncurses=6.3
  - openssl=3.0.0
  - pip=22.0.3
  - python=3.9.10
  - python_abi=3.9
  - readline=8.1
  - setuptools=60.9.3
  - sqlite=3.37.0
  - tk=8.6.12
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - cycler==0.11.0
    - fonttools==4.29.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - numpy==1.22.2
    - packaging==21.3
    - pandas==1.4.1
    - pillow==9.0.1
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - scikit-learn==1.1.1
    - scipy==1.8.0
    - six==1.16.0
    - skorch==0.11.0
    - threadpoolctl==3.1.0
    - torch==1.10.2
    - tqdm==4.64.0
    - typing-extensions==4.1.1
